services:
  slash:
    image: yourselfhosted/slash:latest
    container_name: slash
    ports:
      - 5231:5231
    volumes:
      - slash:/var/opt/slash
    restart: unless-stopped

  umami:
    image: ghcr.io/umami-software/umami:latest
    container_name: umami
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: ${UMAMI_DATABASE_URL}
      APP_SECRET: ${UMAMI_APP_SECRET}
      TWO_FACTOR_ENCRYPTION_KEY: ${UMAMI_TWO_FACTOR_ENCRYPTION_KEY}
    depends_on:
      umami-db:
        condition: service_healthy
    init: true

  umami-db:
    image: postgres:15-alpine
    container_name: umami-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${UMAMI_DB_NAME}
      POSTGRES_USER: ${UMAMI_DB_USER}
      POSTGRES_PASSWORD: ${UMAMI_DB_PASSWORD}
    volumes:
      - umami:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  translink:
    image: ghcr.io/linuskang/translink-app:latest
    container_name: translink
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      VEHICLE_API_URL: http://translink-api:8000/v1/seq/vehicle_positions
      NEXT_PUBLIC_MAPTILER_KEY: ${TRANSLINK_MAPTILER_KEY}
    depends_on:
      translink-api:
        condition: service_healthy

  translink-api:
    image: ghcr.io/linuskang/translink-api:latest
    container_name: translink-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    volumes:
      - translink:/app/data
  
  dicebear:
    image: dicebear/api:4
    container_name: dicebear
    restart: unless-stopped
    ports:
      - '5700:3000'
    tmpfs:
      - '/run'
      - '/tmp'

volumes:
  slash:
  umami:
  translink: